openapi: 3.0.1
info:
  title: "jMedia API"
  version: 1.0.0
paths:
  /feedback:
    get:
      description: "Get all feedbacks"
      tags:
        - Feedback
        - User
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/FullFeedbackResponse"
    post:
      description: "Create a new feedback"
      tags:
        - Feedback
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedbackRequest"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/FullFeedbackResponse"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "null"
                    success: false
        "409":
          description: "Conflict"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "null"
                    success: false
        "400":
          description: "Bad Request"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "null"
                    success: false
  /feedback/upload/{id}:
    post:
      description: "Create a new feedback"
      tags:
        - Feedback
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "integer"
      responses:
        "200":
          description: ""
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "null"
                    success: false
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "null"
                    success: false
components:
  schemas:
    FullFeedbackResponse:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int"
        title:
          type: "string"
        description:
          type: "string"
        type:
            $ref: "#/components/schemas/FeedbackType"
        filesUrl:
          type: "array"
          items:
            type: "string"
    FeedbackRequest:
      type: "object"
      properties:
        title:
          type: "string"
        description:
          type: "string"
        type:
          $ref: "#/components/schemas/FeedbackType"
      required:
      - "title"
      - "description"
      - "type"
    ErrorResponse:
      type: "object"
      properties:
        message:
          type: "string"
        success:
          type: "boolean"
    FeedbackType:
      type: string
      enum:
        - bug
        - feature
        - other