ktor:
  development: $DEV_MODE
  deployment:
    port: 8080
  application:
    modules:
      - com.jmedia.ApplicationKt.module

database:
  url: $DB_URL
  driver: $DB_DRIVER
  user: $DB_USER
  password: $DB_PASSWORD