ktor:
  development: $DEV_MODE
  deployment:
    port: 8080
  application:
    modules:
      - com.jmedia.ApplicationKt.module

database:
  driver: $DB_DRIVER
  cache:
    url: $CACHE_DB_URL
    user: $CACHE_DB_USER
    password: $CACHE_DB_PASSWORD

#minio:
#  endpoint: $MINIO_ENDPOINT
#  accessKey: $MINIO_ACCESS_KEY
#  secretKey: $MINIO_SECRET_KEY