ktor:
  development: $DEV_MODE
  deployment:
    port: 8080
  application:
    modules:
      - com.jmedia.ApplicationKt.module

#database:
#  url: $DB_URL
#  driver: $DB_DRIVER
#  user: $DB_USER
#  password: $DB_PASSWORD

#minio:
#  endpoint: $MINIO_ENDPOINT
#  accessKey: $MINIO_ACCESS_KEY
#  secretKey: $MINIO_SECRET_KEY